# -*- coding: utf-8 -*-
"""19660_Mahmud_Omer_q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-kub7JA4cz7caaqrjrAzCdemi9wlKihT
"""

#Define a function in recursion to check if there is a digit in positive number argument, 
#which is the same as a single bit target value, or not
#def has_seven(k, target):
"""Returns True if at least one of the digits of k is a 7if target is 7, False otherwise.
    >>> has_seven(3, 7)
    False
    >>> has_seven(7, 7)
    True
    >>> has_seven(2734, 7)
    True
    >>> has_seven(2634, 7)
    False
    >>> has_seven(734, 7)
    True
    >>> has_seven(7777, 7)
    True
    """
#ANS

def has_seven(k, target):
    if k==target or k%10 == target:
      return True 
    elif k == 0:
      return False
    else:
      return has_seven(k//10,target)


print(has_seven(3, 7))
print(has_seven(7, 7))
print(has_seven(2734, 7))
print(has_seven(2634, 7))
print(has_seven(734, 7))
print(has_seven(777, 7))